name: login
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.13.0
  cloud_firestore: ^3.1.9
  firebase_database: ^9.0.7
  image_picker: ^0.8.4+9
#  firebase_messaging_platform_interface: "3.1.5"

  cupertino_icons: ^1.0.2
  firebase_storage: ^10.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  change_app_package_name: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/default_image.jpg
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
